BITIYA_WebSite/BITIYA_WebSite/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BITIYA_WebSite.Controllers
{
    //This is the main controller for bitiya

    public class DefaultController : Controller
    {
        //
        // GET: /Default/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Bitiya_Paypal()
        {
            
            return View();
        }

    }
}

BITIYA_WebSite/BITIYA_WebSite/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Web.UI.HtmlControls;
using System.IO;
using System.Web.UI;
using BITIYA_WebSite.Models;

namespace BITIYA_WebSite.Controllers
{
    public class GalleryController : Controller
    {
        //
        // GET: /Gallery/

        public ActionResult Index()
        {
            string imagesPath = "Wowslider/Events/HolmdelWalkathon/data1/images";
            string ttPath = "Wowslider/Events/HolmdelWalkathon/data1/tooltips";

            string MappedPath = Server.MapPath("~/" + imagesPath);

            DirectoryInfo imagesDirectory = new DirectoryInfo(MappedPath);

            FileInfo[] imagesInfo = imagesDirectory.GetFiles();

            IEnumerable<string> imgFiles = imagesInfo.Select(f => f.Name);
            ViewBag.imagePath = "../../" + imagesPath + "/";
            ViewBag.ttPath = "../../" + ttPath + "/";

            List<WowSliderClass> fc = new List<WowSliderClass>();
            foreach (string str in imgFiles)
            {
                WowSliderClass f = new WowSliderClass();
                f.imageName = str;
                f.ttName = str.ToLower();
                fc.Add(f);
            }

            ViewBag.tts = imgFiles.ToString().ToLower();
            return View(fc);
            //return View(fc);

        }
 
        
    }

    
}

BITIYA_WebSite/BITIYA_WebSite/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BITIYA_WebSite.Models;
using System.IO;

namespace BITIYA_WebSite.Controllers
{
    public class ProjectsController : Controller
    {
        //
        // GET: /Projects/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ppes()
        {
            string ppesimagesPath = "Wowslider/Projects/PPES/data1/images";
            string ppesttPath = "Wowslider/Projects/PPES/data1/tooltips";
            List<WowSliderClass> wsclist = GetImages(ppesimagesPath, ppesttPath);
            return View(wsclist);
        }

        public ActionResult bvk()
        {
            string bvkimagesPath = "Wowslider/Projects/BVK/data1/images";
            string bvkttPath = "Wowslider/Projects/BVK/data1/tooltips";
            List<WowSliderClass> wsclist = GetImages(bvkimagesPath, bvkttPath);
            
            return View(wsclist);
        }

        public List<WowSliderClass> GetImages(string imagesPath, string ttPath)
        {
            

            string MappedPath = Server.MapPath("~/" + imagesPath);

            DirectoryInfo imagesDirectory = new DirectoryInfo(MappedPath);

            FileInfo[] imagesInfo = imagesDirectory.GetFiles();

            IEnumerable<string> imgFiles = imagesInfo.Select(f => f.Name);
            ViewBag.imagePath = "../../" + imagesPath + "/";
            ViewBag.ttPath = "../../" + ttPath + "/";

            List<WowSliderClass> fc = new List<WowSliderClass>();
            foreach (string str in imgFiles)
            {
                WowSliderClass f = new WowSliderClass();
                f.imageName = str;
                f.ttName = str.ToLower();
                fc.Add(f);
            }

            ViewBag.tts = imgFiles.ToString().ToLower();

            return fc;
        }

    }
}

BITIYA_WebSite/BITIYA_WebSite/Views/Default/Bitiya_Paypal.cshtml
@{
    ViewBag.Title = "Bitiya_Paypal";
}

    <script type="text/jscript">
        document.domain = "bitiyaanmol.org";
    </script>

<div class="main">
    <div id="mission">
        <p>
            Donate to support girls to build a better life for themselves, their families and
            their communities at large. Every one of your dollars is an investment towards providing
            a building block for a girl’s life. Donations made on our site are redirected to
            a secure section of PayPal.com to complete the payment portion of the donation transaction.
            Data sent to PayPal.com is encrypted using SSL technology, the most widely used
            data encryption coding system for secure e-commerce transactions. If you still have
            any concerns about donating online, feel free to speak to us at 1 732 688 7249.
            Your contribution is tax-deductible as described on your receipt and to the extent
            allowed by law. Bitiya is organized under the laws of the state of New Jersey, United
            States and is a nonprofit 501(c)(3) organization. EIN/tax ID number: 26-1416681
            . In order to ensure a high level of transparency and accountability we would like
            to give you an insight into our donation receipts. We want to <strong>thank you sincerely</strong>
            for all the received donations. We look forward to presenting you with the successful
            progress.
        </p>
    </div>
    <table>
        <tr>
            <td valign="top" style="padding-top: 30px; padding-left: 150px">
                <table border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <td width="597">
                            <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                            <input type="hidden" name="cmd" value="_s-xclick">
                            <input type="hidden" name="hosted_button_id" value="44H6AEHN22DCQ">
                            <input type="image" src="https://www.paypalobjects.com/WEBSCR-640-20110401-1/en_US/i/btn/btn_donateCC_LG.gif"
                                border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                            <img alt="" border="0" src="https://www.paypalobjects.com/WEBSCR-640-20110401-1/en_US/i/scr/pixel.gif"
                                width="1" height="1">
                            </form>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>

BITIYA_WebSite/BITIYA_WebSite/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="MainContent">

<div id="banner">
    <img src="~/Content/Images/banner_1.png" />
</div>
<div id="upcomig_main">
    <div id="upcomig_left">
    </div>
    <div id="upcoming_center">
        <p class="heading">
            Walkathon in Holmdel</p>
        <p class="main_content">
            Walkathon was a great success ! we had numerous people turned out to support and
            walk with us for the cause. People felt motivated, came forward to help and contribute.
            Thanks everyone for showing up, some photos <a href="@Url.Action("Index", "Gallery")" title="Gallery" target="_self"
                class="content_nav"> here.</a>
            <br />
        </p>
        
    </div>
    <div id="upcomig_right">
    </div>
</div>
<div id="bottom_coloum_main">
    <div class="bottom_coloum">
        <div class="bottom_left">
        </div>
        <div class="bottom_middle">
            <img alt="ppes" src="~/Content/Images/ppes.png" width="164" height="39" class="upcoming" />
            <img alt="ppesImage" src="~/Content/Images/Img1.png" width="277" height="155" class="img1" />
            <p class="text_coloum">
                Pardada Pardadi Educational Society. A project in partnership to give girls the gift of education , 
                thus ending a generation of illiteracy.                                
                @Html.ActionLink("More....", "ppes", "Projects", null, new { @class = "content_nav" })
            </p>
        </div>
        <div class="bottom_right">
        </div>
    </div>
    
    <div class="bottom_coloum" style="margin-left: 2px;">
        <div class="bottom_left">
        </div>
        <div class="bottom_middle">
            <p>
                <img alt="bitiya vikas" src="~/Content/Images/bitya_vikas.png" width="164" height="39" class="upcoming" /></p>
                <img alt="image" src="~/Content/Images/Img2.png" width="273" height="155" class="img1" />
            <p class="text_coloum">
                Brick by brick, help us build a vocational training school for girls to provide
                training on computers, embroidery, sewing, beauty, etc. 
                @Html.ActionLink("More....", "bvk", "Projects", null, new { @class = "content_nav" })
            </p>
        </div>
        <div class="bottom_right">
        </div>
    </div>
</div>
</div>