BITIYA_WebSite/BITIYA_WebSite/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BITIYA_WebSite.Controllers
{
    //This is the main controller for bitiya

    public class DefaultController : Controller
    {
        //
        // GET: /Default/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Bitiya_Paypal()
        {
            
            return View();
        }

    }
}

BITIYA_WebSite/BITIYA_WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>:: Bitiya : BRINGING UP INDEPENDANT TALENTED INSIGHTFUL YOUNG ADULTS ::</title>
        <script src="../../Scripts/jquery-1.9.1-vsdoc.js" type="text/javascript"></script>
        <script src="../../Scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
        <script src="../../Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
        <script src="../../Scripts/jquery.validate.min.js" type="text/javascript"></script>
        <link href="~/Content/Site.css?v=1.1" rel="stylesheet" type="text/css" />
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
       @* @Styles.Render("../../Content/css")*@
       @* @Scripts.Render("~/bundles/modernizr")*@
    </head>
    <body id="body">
         <div id="wraper">

             <div id="header">
                 <div id="logo">
                     <img src="~/Content/Images/Bitiya_logo.png" alt="Bitiya" width="259" height="126" class="logo" /></div>
                 <div id="main_img">
                     <img src="~/Content/Images/girl.jpg" alt="Girl" width="294" height="179" /></div>
                 <div id="donate">

                     <a id="Map" href="@Url.Action("Bitiya_Paypal", "Default")" title="Donate">
                         <img src="~/Content/Images/bitiya_Donate.png" alt="Donate" width="65" height="64" border="0" usemap="#Map" class="donation" />
                     </a>
                     
                 </div>
             </div>

             <div id="slogan">
                 <p class="slogan">
                     BRINGING UP INDEPENDANT TALENTED INSIGHTFUL YOUNG ADULTS
                 </p>
             </div>

             <div id="navigation_main">
                 <div id="nav_left">
                 </div>
                 <div id="nav_middle">
                     <ul class="topmenu" id="menu">
                         <li class="li_main"> @Html.ActionLink("HOME", "Index", new { controller = "Default" }, new { @class = "main_nav" })</li>      
                         <li class="li_main"> @Html.ActionLink("MISSION", "Index", new {controller= "Mission"}, new { @class = "main_nav" })</li>
                         <li class="li_main"> @Html.ActionLink("EVENTS", "Index", new { controller = "Events"}, new { @class = "main_nav" })</li>
                         <li class="li_main"> @Html.ActionLink("PROJECTS", "Index", new { controller = "Projects"}, new { @class = "main_nav" })</li>
                         <li class="li_main"> @Html.ActionLink("GALLERY", "Index", new { controller = "Gallery"}, new { @class = "main_nav" })</li>
                         <li class="li_main"> @Html.ActionLink("NEWSLETTER", "Index", new { controller = "Newsletter"}, new { @class = "main_nav" })</li>
                         <li class="li_main"> @Html.ActionLink("FINANCIALS", "Index", new { controller = "Financials"}, new { @class = "main_nav" })</li>
                         <li class="li_main"> @Html.ActionLink("GET INVOLVED", "Index", new { controller = "Getinvolved" }, new { @class = "main_nav" })</li>
                     </ul>
                 </div>
                 <div id="nav_right">
                 </div>
             </div>


             <div class="main">
                @RenderBody()
            </div>
         

          <div>
            <p class="copyright">
                Copyright © 2012 Bitiya. All Rights Reserved. Photographs of projects by Tanya Bhargava.
            </p>
            <img src="~/Content/Images/fb.png" alt="facebook" width="34" height="35"  border="0" usemap="#Map2"
                class="fb" />
            <map name="Map2" id="Map2">
                <area alt="Area" shape="rect" coords="1,1,32,80" href="http://www.facebook.com/Bitiya" />
            </map>
          </div>
         </div>
        

@*        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)*@
    </body>
</html>